### ISSUE TITLE
Format datepicker

### ISSUE THREAD

**Issue by caspahouzer** [obscure-com/TiActionSheetPicker#4]
Any chance to get the date picker formatted by 24h and lokale?

This ist the normal appcelerator code for a german date. How to do this with your fancy picker?

```
var picker = Ti.UI.createPicker({
        type: Ti.UI.PICKER_TYPE_DATE_AND_TIME,
        format24: true,
        locale: Ti.Platform.locale,
        minDate: minDate,
        maxDate: maxDate,
        value: value,
        bottom: 0,
        selectionIndicator: true,
        width: Ti.UI.FILL
    });
```

I tried this

```
var datePicker = TiActionSheetPicker.createDatePickerSheet({
            title: "Pick a Date",
            mode: Ti.UI.PICKER_TYPE_DATE_AND_TIME,
            initialDate: new Date(2013, 4, 14),
            format24: true,
            locale: Ti.Platform.locale,
            hideCancel: false
        });
```

And one other thing: The "hideCancel" parameter does not work. What can I do to show the cancel button

**Comment by pegli** [comment]
I've added support for the locale, minDate, and maxDate properties, so grab the latest code and try it out.  Please note that format24 is Android-only and is not supported by this iOS module.  Changing the locale to "de_DE" should give you 24-hour format, however.

I will have to make some more significant changes to the module in order to properly support the cancel button for the date picker.  For some reason, the date picker controller in the underlying library was not designed to notify when cancel is clicked.  The module needs a notification in order to clean up resources.

**Comment by caspahouzer** [comment]
looks great. thanks!

Am 15.04.2013 um 18:03 schrieb Paul Mietz Egli notifications@github.com:
